version: "3"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx-proxy/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
  nginx:
    image: study-ecs-fargate/nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx/local/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - CERT_NAME=local-api.dpk3-developers.com
      - VIRTUAL_HOST=local-api.dpk3-developers.com
    depends_on:
      - laravel
  laravel:
    image: study-ecs-fargate/laravel:latest
    container_name: laravel
