version: "3"

services:
  nginx:
    image: study-ecs-fargate/nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx/local/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - laravel
  laravel:
    image: study-ecs-fargate/laravel:latest
    container_name: laravel
